#!/usr/bin/env python

import pytest
import vt
import os

@pytest.fixture(scope="module")
def virus_total_eicar_detection():
    return {
        "Bkav": {
            "category": "malicious",
            "engine_name": "Bkav",
            "engine_version": "1.3.0.9899",
            "result": "W32.Eicar.Worm",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "Elastic": {
            "category": "malicious",
            "engine_name": "Elastic",
            "engine_version": "4.0.17",
            "result": "eicar",
            "method": "blacklist",
            "engine_update": "20210217",
        },
        "MicroWorld-eScan": {
            "category": "malicious",
            "engine_name": "MicroWorld-eScan",
            "engine_version": "14.0.409.0",
            "result": "EICAR-Test-File",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "FireEye": {
            "category": "malicious",
            "engine_name": "FireEye",
            "engine_version": "32.44.1.0",
            "result": "EICAR-Test-File (not a virus)",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "CAT-QuickHeal": {
            "category": "malicious",
            "engine_name": "CAT-QuickHeal",
            "engine_version": "14.00",
            "result": "EICAR.TestFile",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "McAfee": {
            "category": "malicious",
            "engine_name": "McAfee",
            "engine_version": "6.0.6.653",
            "result": "EICAR test file",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "Malwarebytes": {
            "category": "undetected",
            "engine_name": "Malwarebytes",
            "engine_version": "4.2.1.18",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "Zillya": {
            "category": "malicious",
            "engine_name": "Zillya",
            "engine_version": "2.0.0.4315",
            "result": "EICAR.TestFile",
            "method": "blacklist",
            "engine_update": "20210312",
        },
        "SUPERAntiSpyware": {
            "category": "malicious",
            "engine_name": "SUPERAntiSpyware",
            "engine_version": "5.6.0.1032",
            "result": "NotAThreat.EICAR[TestFile]",
            "method": "blacklist",
            "engine_update": "20210312",
        },
        "Sangfor": {
            "category": "malicious",
            "engine_name": "Sangfor",
            "engine_version": "2.9.0.0",
            "result": "EICAR-Test-File",
            "method": "blacklist",
            "engine_update": "20210311",
        },
        "K7AntiVirus": {
            "category": "malicious",
            "engine_name": "K7AntiVirus",
            "engine_version": "11.169.36702",
            "result": "EICAR_Test_File",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "Alibaba": {
            "category": "malicious",
            "engine_name": "Alibaba",
            "engine_version": "0.3.0.5",
            "result": "Trojan:MacOS/eicar.com",
            "method": "blacklist",
            "engine_update": "20190527",
        },
        "K7GW": {
            "category": "malicious",
            "engine_name": "K7GW",
            "engine_version": "11.169.36702",
            "result": "EICAR_Test_File",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "Trustlook": {
            "category": "type-unsupported",
            "engine_name": "Trustlook",
            "engine_version": "1.0",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "Arcabit": {
            "category": "malicious",
            "engine_name": "Arcabit",
            "engine_version": "1.0.0.881",
            "result": "EICAR-Test-File (not a virus)",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "Baidu": {
            "category": "malicious",
            "engine_name": "Baidu",
            "engine_version": "1.0.0.2",
            "result": "Win32.Test.Eicar.a",
            "method": "blacklist",
            "engine_update": "20190318",
        },
        "Cyren": {
            "category": "malicious",
            "engine_name": "Cyren",
            "engine_version": "6.3.0.2",
            "result": "EICAR_Test_File",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "SymantecMobileInsight": {
            "category": "malicious",
            "engine_name": "SymantecMobileInsight",
            "engine_version": "2.0",
            "result": "ALG:EICAR Test String",
            "method": "blacklist",
            "engine_update": "20210126",
        },
        "TotalDefense": {
            "category": "malicious",
            "engine_name": "TotalDefense",
            "engine_version": "37.1.62.1",
            "result": "the EICAR test string",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "APEX": {
            "category": "malicious",
            "engine_name": "APEX",
            "engine_version": "6.142",
            "result": "EICAR Anti-Virus Test File",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "Avast": {
            "category": "malicious",
            "engine_name": "Avast",
            "engine_version": "21.1.5827.0",
            "result": "EICAR Test-NOT virus!!!",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "ClamAV": {
            "category": "malicious",
            "engine_name": "ClamAV",
            "engine_version": "0.103.1.0",
            "result": "Win.Test.EICAR_HDB-1",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "Kaspersky": {
            "category": "malicious",
            "engine_name": "Kaspersky",
            "engine_version": "15.0.1.13",
            "result": "EICAR-Test-File",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "BitDefender": {
            "category": "malicious",
            "engine_name": "BitDefender",
            "engine_version": "7.2",
            "result": "EICAR-Test-File (not a virus)",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "NANO-Antivirus": {
            "category": "malicious",
            "engine_name": "NANO-Antivirus",
            "engine_version": "1.0.146.25265",
            "result": "Marker.Dos.EICAR-Test-File.dyb",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "Paloalto": {
            "category": "type-unsupported",
            "engine_name": "Paloalto",
            "engine_version": "1.0",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "AegisLab": {
            "category": "malicious",
            "engine_name": "AegisLab",
            "engine_version": "4.2",
            "result": "Test.File.EICAR.y",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "Tencent": {
            "category": "malicious",
            "engine_name": "Tencent",
            "engine_version": "1.0.0.1",
            "result": "EICAR.TEST.NOT-A-VIRUS",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "Ad-Aware": {
            "category": "malicious",
            "engine_name": "Ad-Aware",
            "engine_version": "3.0.16.117",
            "result": "EICAR-Test-File (not a virus)",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "TACHYON": {
            "category": "malicious",
            "engine_name": "TACHYON",
            "engine_version": "2021-03-13.02",
            "result": "EICAR-Test-File",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "Sophos": {
            "category": "malicious",
            "engine_name": "Sophos",
            "engine_version": "1.0.2.0",
            "result": "EICAR-AV-Test",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "Comodo": {
            "category": "malicious",
            "engine_name": "Comodo",
            "engine_version": "33341",
            "result": "Malware@#2975xfk8s2pq1",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "F-Secure": {
            "category": "undetected",
            "engine_name": "F-Secure",
            "engine_version": "12.0.86.52",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "DrWeb": {
            "category": "malicious",
            "engine_name": "DrWeb",
            "engine_version": "7.0.49.9080",
            "result": "EICAR Test File (NOT a Virus!)",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "VIPRE": {
            "category": "malicious",
            "engine_name": "VIPRE",
            "engine_version": "91058",
            "result": "EICAR (v)",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "TrendMicro": {
            "category": "malicious",
            "engine_name": "TrendMicro",
            "engine_version": "11.0.0.1006",
            "result": "Eicar_test_file",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "McAfee-GW-Edition": {
            "category": "malicious",
            "engine_name": "McAfee-GW-Edition",
            "engine_version": "v2019.1.2+3728",
            "result": "EICAR test file",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "Trapmine": {
            "category": "type-unsupported",
            "engine_name": "Trapmine",
            "engine_version": "3.5.0.1023",
            "result": None,
            "method": "blacklist",
            "engine_update": "20200727",
        },
        "CMC": {
            "category": "malicious",
            "engine_name": "CMC",
            "engine_version": "2.10.2019.1",
            "result": "Eicar.test.file",
            "method": "blacklist",
            "engine_update": "20210312",
        },
        "Emsisoft": {
            "category": "malicious",
            "engine_name": "Emsisoft",
            "engine_version": "2018.12.0.1641",
            "result": "EICAR-Test-File (not a virus) (B)",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "SentinelOne": {
            "category": "malicious",
            "engine_name": "SentinelOne",
            "engine_version": "5.0.0.20",
            "result": "Static AI - Malicious COM",
            "method": "blacklist",
            "engine_update": "20210215",
        },
        "Avast-Mobile": {
            "category": "malicious",
            "engine_name": "Avast-Mobile",
            "engine_version": "210313-00",
            "result": "Eicar",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "ESET-NOD32": {
            "category": "malicious",
            "engine_name": "ESET-NOD32",
            "engine_version": "22959",
            "result": "Eicar test file",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "Webroot": {
            "category": "malicious",
            "engine_name": "Webroot",
            "engine_version": "1.0.0.403",
            "result": "W32.Eicar.Testvirus.Gen",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "Avira": {
            "category": "malicious",
            "engine_name": "Avira",
            "engine_version": "8.3.3.12",
            "result": "Eicar-Test-Signature",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "eGambit": {
            "category": "type-unsupported",
            "engine_name": "eGambit",
            "engine_version": None,
            "result": None,
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "Antiy-AVL": {
            "category": "undetected",
            "engine_name": "Antiy-AVL",
            "engine_version": "3.0.0.1",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "Kingsoft": {
            "category": "undetected",
            "engine_name": "Kingsoft",
            "engine_version": "2017.9.26.565",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "Gridinsoft": {
            "category": "malicious",
            "engine_name": "Gridinsoft",
            "engine_version": "1.0.31.122",
            "result": "PUP.U.EICAR_Test_File.dd",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "Microsoft": {
            "category": "malicious",
            "engine_name": "Microsoft",
            "engine_version": "1.1.17900.7",
            "result": "Virus:DOS/EICAR_Test_File",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "ViRobot": {
            "category": "malicious",
            "engine_name": "ViRobot",
            "engine_version": "2014.3.20.0",
            "result": "EICAR-test",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "ZoneAlarm": {
            "category": "undetected",
            "engine_name": "ZoneAlarm",
            "engine_version": "1.0",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "GData": {
            "category": "malicious",
            "engine_name": "GData",
            "engine_version": "A:25.28924B:27.22274",
            "result": "EICAR_TEST_FILE",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "Cynet": {
            "category": "malicious",
            "engine_name": "Cynet",
            "engine_version": "4.0.0.25",
            "result": "Malicious (score: 85)",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "BitDefenderFalx": {
            "category": "type-unsupported",
            "engine_name": "BitDefenderFalx",
            "engine_version": "2.0.936",
            "result": None,
            "method": "blacklist",
            "engine_update": "20200916",
        },
        "AhnLab-V3": {
            "category": "malicious",
            "engine_name": "AhnLab-V3",
            "engine_version": "3.19.5.10130",
            "result": "Virus/EICAR_Test_File",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "Acronis": {
            "category": "type-unsupported",
            "engine_name": "Acronis",
            "engine_version": "1.1.1.81",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210211",
        },
        "BitDefenderTheta": {
            "category": "malicious",
            "engine_name": "BitDefenderTheta",
            "engine_version": "7.2.37796.0",
            "result": "EICAR-Test-File (not a virus)",
            "method": "blacklist",
            "engine_update": "20210304",
        },
        "ALYac": {
            "category": "malicious",
            "engine_name": "ALYac",
            "engine_version": "1.1.3.1",
            "result": "Misc.Eicar-Test-File",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "MAX": {
            "category": "malicious",
            "engine_name": "MAX",
            "engine_version": "2019.9.16.1",
            "result": "malware (ai score=100)",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "VBA32": {
            "category": "malicious",
            "engine_name": "VBA32",
            "engine_version": "4.4.1",
            "result": "EICAR-Test-File",
            "method": "blacklist",
            "engine_update": "20210312",
        },
        "Cylance": {
            "category": "type-unsupported",
            "engine_name": "Cylance",
            "engine_version": "2.3.1.101",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "Zoner": {
            "category": "malicious",
            "engine_name": "Zoner",
            "engine_version": "0.0.0.0",
            "result": "EICAR.Test.File-NoVirus.250",
            "method": "blacklist",
            "engine_update": "20210312",
        },
        "TrendMicro-HouseCall": {
            "category": "malicious",
            "engine_name": "TrendMicro-HouseCall",
            "engine_version": "10.0.0.1040",
            "result": "Eicar_test_file",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "Rising": {
            "category": "malicious",
            "engine_name": "Rising",
            "engine_version": "25.0.0.26",
            "result": "EICAR-Test-File (CLASSIC)",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "Yandex": {
            "category": "malicious",
            "engine_name": "Yandex",
            "engine_version": "5.5.2.24",
            "result": "EICAR_test_file",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "Ikarus": {
            "category": "malicious",
            "engine_name": "Ikarus",
            "engine_version": "0.1.5.2",
            "result": "EICAR-Test-File",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "MaxSecure": {
            "category": "malicious",
            "engine_name": "MaxSecure",
            "engine_version": "1.0.0.1",
            "result": "VIRUS.EICAR.TEST",
            "method": "blacklist",
            "engine_update": "20210306",
        },
        "Fortinet": {
            "category": "malicious",
            "engine_name": "Fortinet",
            "engine_version": "6.2.142.0",
            "result": "EICAR_TEST_FILE",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "AVG": {
            "category": "malicious",
            "engine_name": "AVG",
            "engine_version": "21.1.5827.0",
            "result": "EICAR Test-NOT virus!!!",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "Cybereason": {
            "category": "type-unsupported",
            "engine_name": "Cybereason",
            "engine_version": "1.2.449",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210307",
        },
        "Panda": {
            "category": "malicious",
            "engine_name": "Panda",
            "engine_version": "4.6.4.2",
            "result": "EICAR-AV-TEST-FILE",
            "method": "blacklist",
            "engine_update": "20210313",
        },
        "CrowdStrike": {
            "category": "type-unsupported",
            "engine_name": "CrowdStrike",
            "engine_version": "1.0",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210203",
        },
        "Qihoo-360": {
            "category": "malicious",
            "engine_name": "Qihoo-360",
            "engine_version": "1.0.0.1120",
            "result": "qex.eicar.gen.gen",
            "method": "blacklist",
            "engine_update": "20210313",
        },
    }

@pytest.fixture(scope="module")
def virus_total_no_detetions():
    return {
        "Bkav": {
            "category": "undetected",
            "engine_name": "Bkav",
            "engine_version": "1.3.0.9899",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210122",
        },
        "Elastic": {
            "category": "type-unsupported",
            "engine_name": "Elastic",
            "engine_version": "4.0.16",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210121",
        },
        "MicroWorld-eScan": {
            "category": "undetected",
            "engine_name": "MicroWorld-eScan",
            "engine_version": "14.0.409.0",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210122",
        },
        "FireEye": {
            "category": "undetected",
            "engine_name": "FireEye",
            "engine_version": "32.44.1.0",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210122",
        },
        "CAT-QuickHeal": {
            "category": "undetected",
            "engine_name": "CAT-QuickHeal",
            "engine_version": "14.00",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210122",
        },
        "ALYac": {
            "category": "undetected",
            "engine_name": "ALYac",
            "engine_version": "1.1.3.1",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210122",
        },
        "Malwarebytes": {
            "category": "undetected",
            "engine_name": "Malwarebytes",
            "engine_version": "4.2.1.18",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210122",
        },
        "Zillya": {
            "category": "undetected",
            "engine_name": "Zillya",
            "engine_version": "2.0.0.4277",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210122",
        },
        "Sangfor": {
            "category": "undetected",
            "engine_name": "Sangfor",
            "engine_version": "1.0",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210122",
        },
        "K7AntiVirus": {
            "category": "undetected",
            "engine_name": "K7AntiVirus",
            "engine_version": "11.161.36268",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210122",
        },
        "Alibaba": {
            "category": "type-unsupported",
            "engine_name": "Alibaba",
            "engine_version": "0.3.0.5",
            "result": None,
            "method": "blacklist",
            "engine_update": "20190527",
        },
        "K7GW": {
            "category": "undetected",
            "engine_name": "K7GW",
            "engine_version": "11.161.36275",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210122",
        },
        "Trustlook": {
            "category": "type-unsupported",
            "engine_name": "Trustlook",
            "engine_version": "1.0",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210123",
        },
        "Baidu": {
            "category": "undetected",
            "engine_name": "Baidu",
            "engine_version": "1.0.0.2",
            "result": None,
            "method": "blacklist",
            "engine_update": "20190318",
        },
        "Cyren": {
            "category": "undetected",
            "engine_name": "Cyren",
            "engine_version": "6.3.0.2",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210122",
        },
        "SymantecMobileInsight": {
            "category": "failure",
            "engine_name": "SymantecMobileInsight",
            "engine_version": "2.0",
            "result": None,
            "method": "blacklist",
            "engine_update": "20200813",
        },
        "Symantec": {
            "category": "undetected",
            "engine_name": "Symantec",
            "engine_version": "1.13.0.0",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210122",
        },
        "ESET-NOD32": {
            "category": "undetected",
            "engine_name": "ESET-NOD32",
            "engine_version": "22690",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210122",
        },
        "APEX": {
            "category": "type-unsupported",
            "engine_name": "APEX",
            "engine_version": "6.123",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210122",
        },
        "TrendMicro-HouseCall": {
            "category": "undetected",
            "engine_name": "TrendMicro-HouseCall",
            "engine_version": "10.0.0.1040",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210122",
        },
        "Avast": {
            "category": "undetected",
            "engine_name": "Avast",
            "engine_version": "21.1.5827.0",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210122",
        },
        "ClamAV": {
            "category": "undetected",
            "engine_name": "ClamAV",
            "engine_version": "0.102.3.0",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210122",
        },
        "Kaspersky": {
            "category": "undetected",
            "engine_name": "Kaspersky",
            "engine_version": "15.0.1.13",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210123",
        },
        "BitDefender": {
            "category": "undetected",
            "engine_name": "BitDefender",
            "engine_version": "7.2",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210122",
        },
        "NANO-Antivirus": {
            "category": "undetected",
            "engine_name": "NANO-Antivirus",
            "engine_version": "1.0.146.25255",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210123",
        },
        "ViRobot": {
            "category": "undetected",
            "engine_name": "ViRobot",
            "engine_version": "2014.3.20.0",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210122",
        },
        "SUPERAntiSpyware": {
            "category": "undetected",
            "engine_name": "SUPERAntiSpyware",
            "engine_version": "5.6.0.1032",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210122",
        },
        "Rising": {
            "category": "undetected",
            "engine_name": "Rising",
            "engine_version": "25.0.0.26",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210122",
        },
        "Ad-Aware": {
            "category": "undetected",
            "engine_name": "Ad-Aware",
            "engine_version": "3.0.16.117",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210122",
        },
        "TACHYON": {
            "category": "undetected",
            "engine_name": "TACHYON",
            "engine_version": "2021-01-22.02",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210123",
        },
        "Emsisoft": {
            "category": "undetected",
            "engine_name": "Emsisoft",
            "engine_version": "2018.12.0.1641",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210122",
        },
        "Comodo": {
            "category": "undetected",
            "engine_name": "Comodo",
            "engine_version": "33195",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210122",
        },
        "F-Secure": {
            "category": "undetected",
            "engine_name": "F-Secure",
            "engine_version": "12.0.86.52",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210122",
        },
        "DrWeb": {
            "category": "undetected",
            "engine_name": "DrWeb",
            "engine_version": "7.0.49.9080",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210122",
        },
        "VIPRE": {
            "category": "undetected",
            "engine_name": "VIPRE",
            "engine_version": "89866",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210122",
        },
        "TrendMicro": {
            "category": "undetected",
            "engine_name": "TrendMicro",
            "engine_version": "11.0.0.1006",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210122",
        },
        "McAfee-GW-Edition": {
            "category": "undetected",
            "engine_name": "McAfee-GW-Edition",
            "engine_version": "v2019.1.2+3728",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210123",
        },
        "SentinelOne": {
            "category": "type-unsupported",
            "engine_name": "SentinelOne",
            "engine_version": "4.7.1.1",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210115",
        },
        "Trapmine": {
            "category": "type-unsupported",
            "engine_name": "Trapmine",
            "engine_version": "3.5.0.1023",
            "result": None,
            "method": "blacklist",
            "engine_update": "20200727",
        },
        "CMC": {
            "category": "undetected",
            "engine_name": "CMC",
            "engine_version": "2.10.2019.1",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210122",
        },
        "Sophos": {
            "category": "undetected",
            "engine_name": "Sophos",
            "engine_version": "1.0.2.0",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210122",
        },
        "Paloalto": {
            "category": "type-unsupported",
            "engine_name": "Paloalto",
            "engine_version": "1.0",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210123",
        },
        "GData": {
            "category": "undetected",
            "engine_name": "GData",
            "engine_version": "A:25.28419B:27.21689",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210122",
        },
        "Jiangmin": {
            "category": "undetected",
            "engine_name": "Jiangmin",
            "engine_version": "16.0.100",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210123",
        },
        "Webroot": {
            "category": "type-unsupported",
            "engine_name": "Webroot",
            "engine_version": "1.0.0.403",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210123",
        },
        "Avira": {
            "category": "undetected",
            "engine_name": "Avira",
            "engine_version": "8.3.3.10",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210122",
        },
        "eGambit": {
            "category": "type-unsupported",
            "engine_name": "eGambit",
            "engine_version": None,
            "result": None,
            "method": "blacklist",
            "engine_update": "20210123",
        },
        "Antiy-AVL": {
            "category": "undetected",
            "engine_name": "Antiy-AVL",
            "engine_version": "3.0.0.1",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210122",
        },
        "Kingsoft": {
            "category": "undetected",
            "engine_name": "Kingsoft",
            "engine_version": "2017.9.26.565",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210123",
        },
        "Gridinsoft": {
            "category": "undetected",
            "engine_name": "Gridinsoft",
            "engine_version": "1.0.26.117",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210122",
        },
        "Arcabit": {
            "category": "undetected",
            "engine_name": "Arcabit",
            "engine_version": "1.0.0.881",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210122",
        },
        "AegisLab": {
            "category": "undetected",
            "engine_name": "AegisLab",
            "engine_version": "4.2",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210123",
        },
        "AhnLab-V3": {
            "category": "undetected",
            "engine_name": "AhnLab-V3",
            "engine_version": "3.19.4.10106",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210122",
        },
        "ZoneAlarm": {
            "category": "undetected",
            "engine_name": "ZoneAlarm",
            "engine_version": "1.0",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210123",
        },
        "Avast-Mobile": {
            "category": "type-unsupported",
            "engine_name": "Avast-Mobile",
            "engine_version": "210122-00",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210122",
        },
        "Microsoft": {
            "category": "undetected",
            "engine_name": "Microsoft",
            "engine_version": "1.1.17700.4",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210123",
        },
        "Cynet": {
            "category": "undetected",
            "engine_name": "Cynet",
            "engine_version": "4.0.0.25",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210122",
        },
        "BitDefenderFalx": {
            "category": "type-unsupported",
            "engine_name": "BitDefenderFalx",
            "engine_version": "2.0.936",
            "result": None,
            "method": "blacklist",
            "engine_update": "20200916",
        },
        "TotalDefense": {
            "category": "undetected",
            "engine_name": "TotalDefense",
            "engine_version": "37.1.62.1",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210122",
        },
        "Acronis": {
            "category": "type-unsupported",
            "engine_name": "Acronis",
            "engine_version": "1.1.1.80",
            "result": None,
            "method": "blacklist",
            "engine_update": "20201023",
        },
        "McAfee": {
            "category": "undetected",
            "engine_name": "McAfee",
            "engine_version": "6.0.6.653",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210123",
        },
        "MAX": {
            "category": "undetected",
            "engine_name": "MAX",
            "engine_version": "2019.9.16.1",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210123",
        },
        "VBA32": {
            "category": "undetected",
            "engine_name": "VBA32",
            "engine_version": "4.4.1",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210122",
        },
        "Cylance": {
            "category": "type-unsupported",
            "engine_name": "Cylance",
            "engine_version": "2.3.1.101",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210123",
        },
        "Zoner": {
            "category": "undetected",
            "engine_name": "Zoner",
            "engine_version": "0.0.0.0",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210122",
        },
        "Tencent": {
            "category": "undetected",
            "engine_name": "Tencent",
            "engine_version": "1.0.0.1",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210123",
        },
        "Yandex": {
            "category": "undetected",
            "engine_name": "Yandex",
            "engine_version": "5.5.2.24",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210121",
        },
        "Ikarus": {
            "category": "undetected",
            "engine_name": "Ikarus",
            "engine_version": "0.1.5.2",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210122",
        },
        "MaxSecure": {
            "category": "undetected",
            "engine_name": "MaxSecure",
            "engine_version": "1.0.0.1",
            "result": None,
            "method": "blacklist",
            "engine_update": "20201212",
        },
        "Fortinet": {
            "category": "undetected",
            "engine_name": "Fortinet",
            "engine_version": "6.2.142.0",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210122",
        },
        "BitDefenderTheta": {
            "category": "undetected",
            "engine_name": "BitDefenderTheta",
            "engine_version": "7.2.37796.0",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210120",
        },
        "Cybereason": {
            "category": "type-unsupported",
            "engine_name": "Cybereason",
            "engine_version": "1.2.449",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210106",
        },
        "Panda": {
            "category": "undetected",
            "engine_name": "Panda",
            "engine_version": "4.6.4.2",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210122",
        },
        "CrowdStrike": {
            "category": "type-unsupported",
            "engine_name": "CrowdStrike",
            "engine_version": "1.0",
            "result": None,
            "method": "blacklist",
            "engine_update": "20190702",
        },
        "Qihoo-360": {
            "category": "undetected",
            "engine_name": "Qihoo-360",
            "engine_version": "1.0.0.1120",
            "result": None,
            "method": "blacklist",
            "engine_update": "20210123",
        },
    }
    return "275a021bbfb6489e54d471899f7db9d1663fc695ec2fe2a2c4538aabf651fd0f"




@pytest.fixture(scope="module")
def sha256_test_hash_1():
    """ Known good SHA-256 hash (of /bin/bash) to test against """
    return "04a484f27a4b485b28451923605d9b528453d6c098a5a5112bec859fb5f2eea9"

@pytest.fixture(scope="module")
def md5_test_hash_1():
    """ Known good SHA-256 hash (of /bin/bash) to test against """
    return "7063c3930affe123baecd3b340f1ad2c"

@pytest.fixture(scope="module")
def sha256_test_hash_eicar():
    """ SHA256 hash of the EICAR "test virus" """
    return "275a021bbfb6489e54d471899f7db9d1663fc695ec2fe2a2c4538aabf651fd0f"

@pytest.fixture(scope="module")
def vt_eicar_response():
    client = vt.Client(os.getenv("API_KEY"))
    eicar = "275a021bbfb6489e54d471899f7db9d1663fc695ec2fe2a2c4538aabf651fd0f"

    return client.get_object(f"/files/{eicar}")
